search:
  paths:
    - "app/controllers"
    - "app/helpers"
    - "app/presenters"
    - "app/views"
    - "app/assets/javascripts"
data:
  read:
     - config/locales/%{locale}.yml
     - config/locales/**/*.%{locale}.yml
ignore_unused:
  - activerecord.*
  - date.*
  - simple_form.*
  - time.*
  - titles.*
