search:
  paths:
    - "app/controllers"
    - "app/helpers"
    - "app/presenters"
    - "app/views"
    - "app/assets/javascripts"
data:
  read:
     - config/locales/*.yml
     - config/locales/**/*.yml
ignore_unused:
  - activerecord.*
  - date.*
  - devise.*
  - simple_form.*
  - time.*
  - titles.*
