search:
  paths:
    - "app/controllers"
    - "app/helpers"
    - "app/presenters"
    - "app/views"
    - "app/assets/javascripts"

ignore_unused:
  - activerecord.*
  - date.*
  - simple_form.*
  - time.*
  - titles.*
